# Generated by Django 4.2.2 on 2023-06-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormSam',
        ),
    ]
